### ISSUE TITLE
install-unity-2.11.0 doesn't have a target for 'net7.0'

### ISSUE THREAD

**Issue by ewanzd** [sttz/homebrew-tap#2]
Since yesterday the newest version of `dotnet` in homebrew is `7.0.100` (https://formulae.brew.sh/formula/dotnet).

This leads to an inconsistency for `install-unity`:

- TargetFramework is `net6.0` (https://github.com/sttz/install-unity/blob/next/Command/Command.csproj)
- But [install-unity.rb](https://github.com/sttz/homebrew-tap/blob/master/Formula/install-unity.rb) install the newest version of dotnet and this is `net7.0`

Could it be possible to fix the version in `install-unity.rb` or update the target framwork in `install-unity` package?

Our error:

```
MSBuild version 17.4.0+18d5aef85 for .NET
  Determining projects to restore...
  Restored <basepath>/install-unity-2.11.0/sttz.InstallUnity/sttz.InstallUnity.csproj (in 2.63 sec).
  Restored <basepath>/install-unity-2.11.0/Command/Command.csproj (in 2.61 sec).
<basepath>/dotnet/7.0.100/libexec/sdk/7.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): error NETSDK1005: Assets file '<basepath>/install-unity-2.11.0/Command/obj/project.assets.json' doesn't have a target for 'net7.0'. Ensure that restore has run and that you have included 'net7.0' in the TargetFrameworks for your project. [<basepath>/install-unity-2.11.0/Command/Command.csproj::TargetFramework=net7.0]

Do not report this issue to Homebrew/brew or Homebrew/core!
```

**Comment by sttz** [comment]
Thanks for the report!

Turns out I tried to be too clever for my own good and made the formula always target the latest version of .Net.
I updated the Formula to target net6.0 explicitly and also set the roll forward behaviour so it can run on the latest runtime.

Let me know if there are any more issues!
